version: 0.0
os: linux
files:
 - source: research
   destination: /tmp/research
hooks:
 BeforeInstall:
   - location: ./.deploy/remove-app.sh
     timeout: 120
     runas: ubuntu
 AfterInstall:
   - location: ./.deploy/add-app.sh
     timeout: 120
     runas: ubuntu
